

piedweb_reservation_order_invoice:
    path:
        en: /invoice/{id}
        fr: /facture/{id}
    controller: PiedWeb\ReservationBundle\Controller\ManageController::showInvoice
    methods:    [GET, HEAD]
    requirements:
        id: '[0-9]+'

piedweb_reservation_user_orders:
    path:
        en: /orders/{id}
        fr: /reservations/{id}
    controller: PiedWeb\ReservationBundle\Controller\ManageController::showOrders
    methods:    [GET, HEAD]
    requirements:
        id: '[0-9]+'
    defaults:
        id: null

piedweb_reservation_user_profile:
    path:
        en: /me/
        fr: /moi/
    controller: PiedWeb\ReservationBundle\Controller\ManageController::editMyInfo
    methods:    [GET, HEAD, POST]
