services:


# --------
# Me
# --------

    PiedWeb\ReservationBundle\PiedWebReservationBundle: ~

    PiedWeb\ReservationBundle\:
        autowire: true
        resource: '../../../src/*'
        exclude: '../../../src/{Repository,Mailer,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    PiedWeb\ReservationBundle\Controller\:
        autowire: true
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']

    PiedWeb\ReservationBundle\Repository\:
        resource: '../../../src/Repository'
        autowire: true
        tags: ['doctrine.repository_service']


    PiedWeb\ReservationBundle\EventListener\PageListener:
        tags:
            - { name: doctrine.orm.entity_listener, entity: '%app.entity_page%', event: preRemove }

    PiedWeb\ReservationBundle\EventListener\InteractiveLoginListener:
        autowire: true
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    piedweb.reservation.registration.listener:
        class: PiedWeb\ReservationBundle\EventListener\RegistrationListener
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

    piedweb_reservation.mailer:
        class: PiedWeb\ReservationBundle\Mailer\Mailer
        arguments: ['@mailer', '@router', '@templating', '%app.email_sender%', '%app.email_sender_name%']

    PiedWeb\ReservationBundle\Mailer\Mailer:
        alias: piedweb_reservation.mailer

# --------
# Repository
# --------

    PiedWeb\ReservationBundle\Repository\BasketRepository:
        arguments: ['@doctrine', '%app.entity_basket%']
        tags:
            - { name: doctrine.repository_service }

    PiedWeb\ReservationBundle\Repository\BasketItemRepository:
        arguments: ['@doctrine', '%app.entity_basket_item%']
        tags:
            - { name: doctrine.repository_service }

    PiedWeb\ReservationBundle\Repository\OrderRepository:
        arguments: ['@doctrine', '%app.entity_order%']
        tags:
            - { name: doctrine.repository_service }

    PiedWeb\ReservationBundle\Repository\OrderItemRepository:
        arguments: ['@doctrine', '%app.entity_order_item%']
        tags:
            - { name: doctrine.repository_service }

    PiedWeb\ReservationBundle\Repository\ProductRepository:
        arguments: ['@doctrine', '%app.entity_product%']
        tags:
            - { name: doctrine.repository_service }

# --------
# Admin
# --------

    piedweb.admin.product:
        class: PiedWeb\ReservationBundle\Admin\ProductAdmin
        arguments: [~, PiedWeb\ReservationBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.product }
        public: true
    piedweb.admin.order:
        class: PiedWeb\ReservationBundle\Admin\OrderAdmin
        arguments: [~, PiedWeb\ReservationBundle\Entity\Order, ~]
        calls:
            - [ setTranslator, [ '@translator' ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.order }
        public: true
    piedweb.admin.orderItem:
        class: PiedWeb\ReservationBundle\Admin\OrderItemAdmin
        arguments: [~, PiedWeb\ReservationBundle\Entity\OrderItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.orderItem }
        public: true
    piedweb.admin.basketItem:
        class: PiedWeb\ReservationBundle\Admin\BasketItemAdmin
        arguments: [~, PiedWeb\ReservationBundle\Entity\BasketItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.basket }
        public: true
