services:


# --------
# Me
# --------

    PiedWeb\ReservationBundle\PiedWebReservationBundle: ~

    PiedWeb\ReservationBundle\:
        autowire: true
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    PiedWeb\ReservationBundle\Controller\:
        autowire: true
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']

    PiedWeb\ReservationBundle\Repository\:
        resource: '../../../src/Repository'
        autowire: true
        tags: ['doctrine.repository_service']


    PiedWeb\ReservationBundle\EventListener\PageListener:
        tags:
            - { name: doctrine.orm.entity_listener, entity: '%app.entity_page%', event: preRemove }

    PiedWeb\ReservationBundle\EventListener\InteractiveLoginListener:
        autowire: true
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    piedweb.reservation.registration.listener:
        class: PiedWeb\ReservationBundle\EventListener\RegistrationListener
        autowire: true
        tags:
            - { name: kernel.event_subscriber }
    # todo
    #PiedWeb\ReservationBundle\EventListener\InteractiveLoginListener:
        #autowire: true
        #tags:
            #- { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }


# --------
# Admin
# --------

    piedweb.admin.product:
        class: PiedWeb\ReservationBundle\Admin\ProductAdmin
        arguments: [~, PiedWeb\ReservationBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.product }
        public: true
    piedweb.admin.order:
        class: PiedWeb\ReservationBundle\Admin\OrderAdmin
        arguments: [~, PiedWeb\ReservationBundle\Entity\Order, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.order }
        public: true
    piedweb.admin.orderItem:
        class: PiedWeb\ReservationBundle\Admin\OrderItemAdmin
        arguments: [~, PiedWeb\ReservationBundle\Entity\OrderItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.orderItem }
        public: true
    piedweb.admin.basketItem:
        class: PiedWeb\ReservationBundle\Admin\BasketItemAdmin
        arguments: [~, PiedWeb\ReservationBundle\Entity\BasketItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.basket }
        public: true
